import { QueryInterface } from 'sequelize';

export default {
    async up (queryInterface: QueryInterface) {
        await queryInterface.bulkInsert('states', [
            { name: 'California', country_id: 1 },
            { name: 'New York', country_id: 1 },
            { name: 'Washington', country_id: 1 },
            { name: 'Massachusetts', country_id: 1 },
            { name: 'Texas', country_id: 1 },
            { name: 'Utah', country_id: 1 },
            { name: 'Georgia', country_id: 1 },
            { name: 'Colorado', country_id: 1 },
            { name: 'Illinois', country_id: 1 },
            { name: 'North Carolina', country_id: 1 },
            { name: 'Arizona', country_id: 1 },
            { name: 'Ontario', country_id: 2 },
            { name: 'British Columbia', country_id: 2 },
            { name: 'Quebec', country_id: 2 },
            { name: 'England', country_id: 3 },
            { name: 'Bavaria', country_id: 4 },
            { name: 'Berlin', country_id: 4 },
            { name: 'Hesse', country_id: 4 },
            { name: 'Karnataka', country_id: 5 },
            { name: 'Maharashtra', country_id: 5 },
            { name: 'Telangana', country_id: 5 },
            { name: 'Tamil Nadu', country_id: 5 },
            { name: 'West Bengal (Kolkata Metro)', country_id: 5 },
            { name: 'Delhi NCR', country_id: 5 },
            { name: 'Andhra Pradesh', country_id: 5 },
            { name: 'Gujarat', country_id: 5 },
            { name: 'Kerala', country_id: 5 },
            { name: 'Punjab', country_id: 5 },
            { name: 'Rajasthan', country_id: 5 },
            { name: 'Uttar Pradesh', country_id: 5 },
            { name: 'Beijing', country_id: 6 },
            { name: 'Shanghai Municipality', country_id: 6 },
            { name: 'Guangdong', country_id: 6 },
            { name: 'Singapore', country_id: 7 },
            { name: 'North Holland', country_id: 8 },
            { name: 'Masovian Voivodeship', country_id: 9 },
            { name: 'Tel Aviv District', country_id: 10 },
            { name: 'Leinster', country_id: 11 },
            { name: 'Île‑de‑France', country_id: 12 },
            { name: 'Catalonia', country_id: 13 },
            { name: 'Hanoi Province', country_id: 14 },
            { name: 'Ho Chi Minh City', country_id: 14 },
            { name: 'Mexico City Federal Entity', country_id: 15 },
            { name: 'Lagos State', country_id: 16 },
            { name: 'Nairobi County', country_id: 17 },
            { name: 'Seoul Metropolitan Area', country_id: 18 },
            { name: 'Dubai Emirate', country_id: 19 },
            { name: 'Abu Dhabi Emirate', country_id: 19 },
            { name: 'New South Wales', country_id: 20 },
            { name: 'Victoria', country_id: 20 },
            { name: 'Queensland', country_id: 20 },
            { name: 'São Paulo', country_id: 21 },
            { name: 'Distrito Federal', country_id: 21 },
            { name: 'Stockholm County', country_id: 22 },
            { name: 'Uusimaa', country_id: 23 },
            { name: 'Tokyo Prefecture', country_id: 24 },
            { name: 'Western Australia', country_id: 20 },
            { name: 'Zürich', country_id: 25 }
        ]);
    },

    async down (queryInterface: QueryInterface) {
        await queryInterface.bulkDelete('states', {}, {});
    }
};
